baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "Test H·U·G·O"
theme = "github-style"

[Author]
    name = "Thibaut Delplanque"
    bio = "Je suis un dev curieux"
    avatar = "img/avatar.png"

[Params]
    subtitle = "Un site français sur le CMS static, HUGO" # Subtitle of your site
    description = "Un site français sur le CMS static, HUGO" # Description of your site
    opengraph = true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
    social_facebook = "username"
    social_twitter = "username"
    social_linkedin = "thibaut@linkedin.lol"
    social_github = "ThitiBobo"
    social_email = "thibaut.delplanque80@gmail.com"
